const DATA = [
  {
    image: "../View/images/rolled-diuner.jpg",
    name: "Rolled Дюнер",
    weight: 500,
    category: "Дюнери",
    price: 6.99,
  },
  {
    image: "../View/images/diuner_average.jpg",
    name: "Дюнер среден",
    weight: 250,
    category: "Дюнери",
    price: 4.4,
  },
  {
    image: "../View/images/diuner_big.jpg",
    name: "Дюнер голям",
    weight: 350,
    category: "Дюнери",
    price: 6.2,
  },
  {
    image: "../View/images/diuner_xl.jpg",
    name: "Дюнер XL",
    weight: 500,
    category: "Дюнери",
    price: 7.4,
  },
  {
    image: "../View/images/diuner-box.jpg",
    name: "Дюнер box",
    weight: 400,
    category: "Дюнери",
    price: 6.99,
  },
  {
    image: "../View/images/diuner-djob.jpg",
    name: "Дюнер джоб",
    weight: 600,
    category: "Дюнери",
    price: 6.99,
  },
  {
    image: "../View/images/porcia-diuner.jpg",
    name: "Дюнер порция",
    weight: 700,
    category: "Дюнери",
    price: 8.99,
  },
  {
    image: "../View/images/burger-s-diuner-meso-i-kartofi.jpg",
    name: "Бургер с месо от дюнер и картофи",
    weight: 350,
    category: "Бургери",
    price: 9.49,
  },
  {
    image: "../View/images/burger-s-teleshko.jpg",
    name: "Бургер с телешко месо",
    weight: 350,
    category: "Бургери",
    price: 9.99,
  },
  {
    image: "../View/images/burger-s-pileshko.jpg",
    name: "Бургер с хрупкаво пилешко",
    weight: 350,
    category: "Бургери",
    price: 9.49,
  },
  {
    image: "../View/images/hrupkavo-pile-s-garnitura-sos-01.jpg",
    name: "Хрупкаво пиле с гарнитура и сос",
    weight: 350,
    category: "Предястия",
    price: 8.99,
  },
];
